### ISSUE TITLE
Issue playing local video

### ISSUE THREAD

**Issue by Jonovono** [piemonte/Player#1]
Hi. I got the example working and now I want to hook it up to play local video files I have in my Documents directory.

Specifically, I have a path like:

```
let ViewControllerVideoPath = "/var/mobile/Containers/Data/Application/5E9673F2-5258-4386-BF17-FAC06E6059AF/Documents/test.mp4"
```

However, when I get it that path it does not play. 

I notice it fails in:

```
                for key in keys {
                var error: NSError?
                let status = self.asset.statusOfValueForKey(key, error:&error)
                if status == .Failed {
                    print("failed")
                    self.playbackState = .Failed
                    self.delegate.playerPlaybackStateDidChange(self)
                    return
                }
            }
```

Am I doing something wrong?

Thanks.

**Comment by sentiasa** [comment]
@plemonte

I tried using your way too, but doesn't work for me. What I did:
- Downloaded video from Vine & called it aaa.mp4
- Drag/Drop it in project
- Added File to Copy Bundles Resources

Then, at the top of ViewController, I added:
```
let path = NSBundle.mainBundle().pathForResource("aaa", ofType:"mp4")!
let videoUrl = NSURL(string: path)!
```

Also, when I put `print(path)` in ViewDidLoad, it gives me the path:
```
/Users/sent/Library/Developer/CoreSimulator/Devices/67160785-1BDB-4046-BD58-A8C448938A4F/data/Containers/Bundle/Application/00750449-71AC-45E5-B74D-B5FA1A516D18/Player.app/aaa.mp4
```

(Please note that, if I give the path a filename that doesn't exists, it throws nil; so I know the video exists)

**Comment by sentiasa** [comment]
Solved with `let videoUrl = NSURL(fileURLWithPath: path)`
