### ISSUE TITLE
Unmirror video preview

### ISSUE THREAD

**Issue by otymartin** [piemonte/Player#102]
@piemonte 
Unfortunately, `AVFoundation` defaults to mirroring videos capturing with the front-facing camera. I've found it impossible to unmirror from the `CameraEngine` library i used to capture the video however was wonder if it's possible to atleast unmirror the preview using player?

**Comment by piemonte** [comment]
hey @otymartin i'm working on a new library that has the feature that will properly allow you to turn off mirroring while recording.

it's possible to achieve this by re-encoding the video but that's out of the scope for this project.

**Comment by piemonte** [comment]
@otymartin i'll send you the link when my new project posts, give me a few days

**Comment by otymartin** [comment]
@piemonte Beautiful.. Thanks🙏

**Comment by otymartin** [comment]
I solved this problem with this
```swift
        self.player.view.transform = CGAffineTransformMakeScale(-1.0, 1.0)
```
