### ISSUE TITLE
Fast init/de-init of Player seems to cause crash

### ISSUE THREAD

**Issue by hellojeffy** [piemonte/Player#103]
I'm not sure if I'm tackling this the correct way, I have a bunch of re-usable cells that each have their own instance of Player, which is initialized when the cell is visible and then deinitialized on reuse via

```
    override func prepareForReuse() {
        super.prepareForReuse()
        player = nil
    }
```

and if I swipe up and down and (my guess is that it is init/de-init the Player very fast during this) the app will crash in the same error as issue #77 in the common init

```
self.timeObserver = self.player.addPeriodicTimeObserverForInterval(CMTimeMake(1, 100), queue: dispatch_get_main_queue()) { [unowned self] time in
            self.delegate?.playerCurrentTimeDidChange(self)
} 
```

0 _swift_abortRetainUnowned

Am I approaching the problem wrong where someone swipes very fast through a cell that is trying to init up the Player, and should be allocating/re-using them a different way?  Because if I swipe slowly everything runs fine, but this is only if I am swiping very fast to cause it to re-init a lot.

Edit: This also occurs if I have for example a cell off screen that will have Player Content, and I swipe too fast.

**Comment by piemonte** [comment]
hey @hellojeffy , thanks for the note. i'd like to move the observer adding out of the init func into when the controller is loaded / unloaded instead. also, we should have the remove being called with a dispatch main to be safe. that should take care of this timing condition you're seeing.

i can update the swift 3 branch for this but i don't have the same setup as you have. if you can test it out once we make the changes, that'd be helpful.

**Comment by piemonte** [comment]
i'll update master too

**Comment by hellojeffy** [comment]
Thanks for the quick turnaround @piemonte !

Tested it and it works great! Thanks for looking into it again.

**Comment by piemonte** [comment]
@hellojeffy 👍
