### ISSUE TITLE
0.1.2 can't be installed on iOS 9

### ISSUE THREAD

**Issue by fjcaetano** [piemonte/Player#104]
To be honest, this sounds like a Cocoapods bug to me, but I'm reporting here because it's the only pod I'm using that is causing this.

Since the [change in the podspec](https://github.com/piemonte/Player/commit/edd89d7110dc713b974e5404fbc6db701437a9e2#diff-e6e7a7c530c8ac33a50a1f44cd6713a9L10) that downgraded the minimum deployment_target from iOS 9 to 8, I wasn't able to install this update in my project that has the Deployment Target set as iOS 9.

Cocoapods is throwing me:
```
[!] Unable to satisfy the following requirements:

- `Player (~> 0.1.2)` required by `Podfile`
- `Player (~> 0.1.2)` required by `Podfile`
- `Player (~> 0.1.2)` required by `Podfile`

Specs satisfying the `Player (~> 0.1.2)` dependency were found, but they required a higher minimum deployment target.
```

Do you think it's an issue with Cocoapods?

**Comment by piemonte** [comment]
@fjcaetano we've updated it back to iOS 8, just pushing the pod now ✌️

**Comment by fjcaetano** [comment]
Were you able to reproduce it?

**Comment by piemonte** [comment]
@fjcaetano i believe 0.1.2 had a case-sensitive issue with the pod, please try it with 0.1.3 and let me know if you still have problems

**Comment by fjcaetano** [comment]
@piemonte that solved it. Thank you very much
