### ISSUE TITLE
PlayerDelegate methods should all be optional

### ISSUE THREAD

**Issue by tsheaff** [piemonte/Player#109]
This way I can pick and choose which ones I care about implementing, rather than all-or-nothing

**Comment by tsheaff** [comment]
For example my implementation requires this:

```swift
extension InlineVideoViewController: PlayerDelegate {
    func playerReady(_ player: Player) {}
    func playerPlaybackStateDidChange(_ player: Player) {}
    func playerBufferingStateDidChange(_ player: Player) {}
    func playerCurrentTimeDidChange(_ player: Player) {}
    func playerPlaybackWillStartFromBeginning(_ player: Player) {}
    func playerWillComeThroughLoop(_ player: Player) {}

    func playerPlaybackDidEnd(_ player: Player) {
        self.dismiss()
    }
}
```

which is a bit silly. This would be preferred:

```swift
extension InlineVideoViewController: PlayerDelegate {
    func playerPlaybackDidEnd(_ player: Player) {
        self.dismiss()
    }
}
```

**Comment by tsheaff** [comment]
@piemonte If I submit a pull-request would it get approved?

**Comment by piemonte** [comment]
hey @tsheaff – yeah that sounds good. 👍

**Comment by tsheaff** [comment]
Looks like it's not desirable.  From [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Protocols.html) in the docs under `Optional Protocol Requirements`:

`Both the protocol and the optional requirement must be marked with the @objc attribute. Note that @objc protocols can be adopted only by classes that inherit from Objective-C classes or other @objc classes. They can’t be adopted by structures or enumerations.`

**Comment by tsheaff** [comment]
@piemonte see https://github.com/piemonte/Player/pull/110
