### ISSUE TITLE
Start playing automatically right after playback was stopped by stop() method

### ISSUE THREAD

**Issue by DragoX** [piemonte/Player#111]
Caused by issue with handling buffering:

`
                    if (bufferedTime - currentTime) >= self.bufferSize {
                        self.playFromCurrentTime()
                    }
`

even if playbackState == .stopped or .paused method self.playFromCurrentTime() still will be called and resume playing.

Bug appears on iOS 10 and master branch.

**Comment by piemonte** [comment]
thanks @DragoX 

let me know if the last commit fixes this issue, i don't have a means to repro it right now.
