### ISSUE TITLE
Playback loop - 0.5 sec black screen between loops?

### ISSUE THREAD

**Issue by ghost** [piemonte/Player#116]
Anybody else experiencing this? Happens 90% of the time.

**Comment by danieldelouya** [comment]
Any news regarding this?

**Comment by piemonte** [comment]
hey @danieldelouya. thanks for the feedback. have you verified the video doesn't have black frames when played locally?

**Comment by danieldelouya** [comment]
@piemonte  Yes I have indeed :)

**Comment by mahmutpinarbasi** [comment]
Hi @piemonte! Any updates on this?

**Comment by piemonte** [comment]
hey @mahmutpinarbasi thanks for the interest. i currently don't have the time to look into this but PR's are welcome.

i will probably pick this up for a new project soon and will address some of the open issues. my guess is that it's related to:

📎 https://github.com/piemonte/Player/issues/75

**Comment by danieldelouya** [comment]
Made a hack for this by seeking to 10 miliseconds after the playback has ended and, then start playing the video again: 

```
  func playerPlaybackDidEnd(_ player: Player) {
        let t1 = CMTimeMake(10, 100)
        self.videoPlayer.seekToTime(t1)
        self.videoPlayer.playFromCurrentTime()        
    }
```

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/Player/issues/123
