### ISSUE TITLE
Player and its properties should be 'open'

### ISSUE THREAD

**Issue by fjcaetano** [piemonte/Player#117]
The `Player` class and it's properties should be `open` instead of `public` to enable subclassing.

**Comment by piemonte** [comment]
https://github.com/piemonte/Player/pull/121

**Comment by fjcaetano** [comment]
I'm sorry for the looong delay. I've being using my fork and only now was able to update.

Shouldn't the Player's properties be `open` as well? That pull request opened the class and its methods, but not its properties.

**Comment by piemonte** [comment]
hey @fjcaetano that sounds good, feel free to submit a PR.
