### ISSUE TITLE
deinit not called when using this library?

### ISSUE THREAD

**Issue by uknowmeright** [piemonte/Player#124]
I am running into performance issues in my app and I believe they are related to this library, or at least how I am using it.

I noticed that deinit is never called on the controller that implements Player!

I have tried a lot of methods for getting it to fire and nothing seems to work:

` dispatch_async(dispatch_get_main_queue()) {
            if self.player != nil{
                self.player!.pause()
                self.player!.stop()
                self.player!.view.removeFromSuperview()
                self.player!.delegate = nil
                self.player = nil
            }
            self.dismissViewControllerAnimated(true, completion: { _ in })
`

this helps with memory but does not completely remove the viewController. any ideas?

**Comment by piemonte** [comment]
hey @uknowmeright thanks for the report. that's interesting, i wonder if some object is registered for KVO and is just being held.

**Comment by piemonte** [comment]
@uknowmeright if you're using this as a child view controller, you'll have to remove it from the VC hierarchy too. I updated the sample project as an example:

commit 497258fe6fedd38542615fb49eeaad8121384812
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Thu Dec 15 19:29:29 2016 -0800

    update sample project

**Comment by uknowmeright** [comment]
hmm. This seems to help a bit. My memory keeps rising each time I reload this view controller and deinit never gets called. Cant help but think there is some kind of memory leak. i will keep investigating. Thanks!

**Comment by slash7** [comment]
I have a similar problem. After dismissing the VC that contains the player, the sound is still playing.

```swift 
override func dismiss(animated flag: Bool, completion: (() -> Void)? = nil) {
    self.player.stop()
    super.dismiss(animated: flag, completion: completion)
}
```

**Comment by pranjaltech** [comment]
Any updates on this? I am facing this issue too.

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/Player/issues/186
