### ISSUE TITLE
Question - multiple videos and looping

### ISSUE THREAD

**Issue by narner** [piemonte/Player#125]
Hey there! First off, thanks for this library - really useful and well done :)

My question is, is it possible to loop multiple videos? So, have my `Player` instance play one video, then go to the next, and then start over again?

I looked through the source of `Player.swift`, but didn't see anything obvious about how to do that. 

Thanks!

**Comment by delta98** [comment]
@narner sounds like you may need an [avqueueplayer](https://developer.apple.com/reference/avfoundation/avqueueplayer) you can replicate the same, by placing your assets/urls in a list, listen for the video stop event in the delegate and then choosing the next asset/url you have in your list and reload the player using `setUrl` it's not elegant, but it's what comes closest to my mind, right now.
