### ISSUE TITLE
Be able to mute the video

### ISSUE THREAD

**Issue by erkie** [piemonte/Player#13]
`AVPlayer` has a `muted` property that I would like to change, but I'm not allowed access to the `player: AVPlayer` property of Player. 

So my feature request (or general question of how to implement), either allow access directly to the `AVPlayer` instance, or add a muted property to mute the audio of a video. :hear_no_evil: 

What do you think?

**Comment by piemonte** [comment]
@erkie hey, nice idea, i can expose `muted`
