### ISSUE TITLE
Pre-download videos before playing

### ISSUE THREAD

**Issue by ryandailey100** [piemonte/Player#133]
Is there a way to pre download multiple videos so that when I would like to play any of them, it would play right away. The video would have to be cached somewhere and have a give URL so that I can set the player.url to the given url. How could this be done? Also can this be done without having any memory issues?

**Comment by danieldelouya** [comment]
@ryandailey100  You can save the downloaded files to the disk using the FileManager + writing Data to a url.

So when you have fetched the video, convert the url to Data, then write that data to a URL locally on your device. 

Try reading up on video caching on eg. Stackoverflow. Hope it helps! :)

**Comment by ryandailey100** [comment]
Thanks!
