### ISSUE TITLE
Crash can be fixed by adding isEmpty check to timeRanges.

### ISSUE THREAD

**Issue by miguellan** [piemonte/Player#134]
![player-pod-changes-for-crash](https://cloud.githubusercontent.com/assets/850108/24473760/9e0200bc-1487-11e7-9f80-ecf3537f2346.png)

Line 580 was added to my pod version of Player.swift, so that I could get past crashes when trying to stream HLS videos from Vimeo.  I think this key/value event occurs, with empty timeRanges sometimes, before it comes through with data?  At least that's what I've seen, and this fix, stops it from crashing the app.  Perhaps, you want to add it, and/or do something more?

**Comment by piemonte** [comment]
hey @miguellan this was fixed in a more recent release.

a399ab7eca3ffedfb47c0303c6ade881e70f8bb0

**Comment by piemonte** [comment]
i appreciate the issue!
