### ISSUE TITLE
Player keeps playing after being dismissed

### ISSUE THREAD

**Issue by otymartin** [piemonte/Player#135]
@piemonte 
I have my `PlayerViewController` embedded in a `NavigationController`. 
`UINavigationController>>CameraViewController>>PlayerViewController`

When I dismiss my `PlayerViewController` with `self.dismiss(animated: true, completion: nil)`
It dismisses the entire NavigationController and goes back to my `RootViewController` but I can still hear my video Looping endlessly in the `PlayerViewController` leading me to believe it was not dismissed.

Here is how I initialize it.

```swift
class PlayerViewController: UIViewController {

var player: Player!

override func viewDidLoad() {
        super.viewDidLoad()
        self.playerSettings()
    }

private func playerSettings() {
        
        self.player = Player()
        
        self.view.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        
        self.player.playerDelegate = self
        self.player.playbackDelegate = self
        self.player.view.frame = self.view.bounds
        
        self.addChildViewController(self.player)
        self.view.addSubview(self.player.view)
        self.player.didMove(toParentViewController: self)
        
        self.player.url = self.videoURL
        self.player.playbackLoops = true
    }
}

**Comment by piemonte** [comment]
hey @otymartin sorry to hear that. may be the result of the deallocation issue, will check it out soon.

📎 https://github.com/piemonte/Player/issues/124

**Comment by piemonte** [comment]
closing this since it's a duplicate, thanks for creating.
