### ISSUE TITLE
Crashing at Start

### ISSUE THREAD

**Issue by jacobo360** [piemonte/Player#136]
Hi, I'm using XCode 8 and Swift 3. The library is crashing at the start because it is coming up with nil at these func:

internal func removePlayerLayerObservers() {
        self._playerView.layer.removeObserver(self, forKeyPath: PlayerReadyForDisplayKey, context: &PlayerLayerObserverContext)
    }

Any ideas of why this might be?

**Comment by iShawnWang** [comment]
same issue here ~

**Comment by piemonte** [comment]
🙌
