### ISSUE TITLE
Can't install pod

### ISSUE THREAD

**Issue by krumjahn** [piemonte/Player#14]
I've installed the cocoa pods prerelease.

Successfully installed cocoapods-0.36.3

When I run pod install for the "Player" pod, it gives me this error

[!] Invalid Podfile file: undefined local variable or method `‘Player’' for #. Updating CocoaPods might fix the issue.

Also, are there any tutorials on how to integrate it with my app? I'm a complete noob to swift.

**Comment by piemonte** [comment]
hey @krumjahn i'll look into this cocoapod issue you're seeing. until then, you can just copy the `Player.swift` file into your project.

**Comment by piemonte** [comment]
hey @krumjahn submitted a new version to cocoa pods. please make sure you've got `use_frameworks!` in your podfile

```ruby
source ‘https://github.com/CocoaPods/Specs.git'
platform :iOS, ‘8.0’
use_frameworks!

pod ‘Player’
```
