### ISSUE TITLE
Thin black border on top of player view

### ISSUE THREAD

**Issue by otymartin** [piemonte/Player#142]
@piemonte 
![18051857_10158561226635608_285956318_n](https://cloud.githubusercontent.com/assets/2222881/25235506/4f9ac21e-25b3-11e7-86b8-e43e05dcf457.jpg)

Above is a picture of me dragging my Player to dismiss it.
As you can see, there is a 1.5-2px thin black stroke at the top of it.

How to remove?

**UPDATE:**
I managed to remove it by commenting out the code below but it needs a more permanent solution 
because the thin stroke returns when I add black background color to my player's superview.
```swift
 override init(frame: CGRect) {
        super.init(frame: frame)
        //self.playerLayer?.backgroundColor = UIColor.black.cgColor
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        //self.playerLayer?.backgroundColor = UIColor.black.cgColor
    }
```

**Comment by piemonte** [comment]
thanks @otymartin will check it out when i have a free moment

**Comment by otymartin** [comment]
@piemonte hey did you ever figure this out?

**Comment by piemonte** [comment]
hey @otymartin the latest update should address this issue. by default, there shouldn't be a color set on the layer. if you want a specific bg color, you just have to explicitly set it now as of '0.9.0'.

thanks for the project support!
