### ISSUE TITLE
Unable to install with Carthage

### ISSUE THREAD

**Issue by eliotfowler** [piemonte/Player#144]
Cartfile:
```
github "piemonte/Player" ~> 0.5.0
```

Carthage command:
```
carthage update --platform iOS --cache-builds
```

Output:
```
*** Fetching Player
*** Checking out Player at "0.5.1"
*** No cache found for Player, building with all downstream dependencies
*** Skipped building Player due to the error:
Dependency "Player" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/piemonte/Player/issues/new
```

If I try running it without the `--platform iOS`, I get the same issue reported in #33:
```
*** Skipped building Player due to the error:
Dependency "Player" has no shared framework schemes
```

I cloned Player locally and tried to debug. I think the easiest path to fixing this will be debugging why the following command fails, which is a pretty standard command line build and indeed what Carthage is using to try to build it with `carthage build --no-skip-current`:
```
/usr/bin/xcrun xcodebuild -workspace /Users/eliotfowler/Code/Libraries/Player/Player.xcworkspace -scheme Player -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build
```

The error reported from this is:
```
~/Library/Developer/Xcode/DerivedData/Player-aixpathpuwzwtebtpryxlkfzvjxs/Build/Intermediates/Player.build/Release-iphoneos/Player.build/unextended-module.modulemap:2:19: error: umbrella header 'Player.h' not found 
    umbrella header "Player.h"
```

After looking into it, I think it might be related to the fact that the umbrella file is named `Player.h` and the targets are named Player_iOS and Player_tvOS. According to [this StackOverflow answer](http://stackoverflow.com/a/39487620/809278) the umbrella file must share the name of the target. Unfortunately, that means we'll need 2 umbrella files for the 2 different targets.

**Comment by swemoney** [comment]
I just submitted a pull request #157 that appears to resolve the Carthage issues. More testing is probably needed.

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/Player/issues/155
