### ISSUE TITLE
Crashes when setting fillMode

### ISSUE THREAD

**Issue by BigSauce** [piemonte/Player#146]
Crash occurs when setting the fillMode prior to the url being set/playFromBeginning() called.

`player.fillMode = FillMode.resizeAspectFill.rawValue`

**Comment by piemonte** [comment]
thanks @BigSauce will check it out. also dig your username. 👍

**Comment by mrfarukturgut** [comment]
I am having the same issue when I call this code in `viewDidLoad`

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/Player/commit/95619d9ec48417ad9e736fb446b23d40f2508db0

**Comment by piemonte** [comment]
i believe i've fixed this with the above commit because i'm not able to reproduce. PlayerLayer def didn't have a property named fillMode, which i believe was the crash.

**Comment by piemonte** [comment]
(let me know if you do still encounter this with 0.9.x)
