### ISSUE TITLE
Two Player instances in the same view controller. 

### ISSUE THREAD

**Issue by thexande** [piemonte/Player#149]
Back again. I am trying to get two player instances within the same view controller to play on `viewDidAppear()`.

The following technique has worked great with a single player instance, so in theory this should work fine. 

So far, my strategy has been the following.

1. Programatic player instances: 

```swift
    let optionOnePlayer: Player = {
        let player = Player()
        player.playbackFreezesAtEnd = true
        player.view.translatesAutoresizingMaskIntoConstraints = false
        return player
    }()
    
    let optionTwoPlayer: Player = {
        let player = Player()
        player.playbackFreezesAtEnd = true
        player.view.translatesAutoresizingMaskIntoConstraints = false
        return player
    }()
```

2. Containment views:
```swift
    
    lazy var optionOnePlayerView: UIView = {
        let view = UIView()
        view.addSubview(self.optionOnePlayer.view)
        view.backgroundColor = .green
        view.layer.cornerRadius = 4
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    lazy var optionTwoPlayerView: UIView = {
        let view = UIView()
        view.backgroundColor = .green
        view.addSubview(self.optionTwoPlayer.view)
        view.layer.cornerRadius = 4
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()

    lazy var playerViews: UIView = {
        let view = UIView()
        view.addSubview(self.optionOnePlayerView)
        view.addSubview(self.optionTwoPlayerView)
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
```

3. Add constraints to pin bounds of player views to containment views:
```swift
  NSLayoutConstraint.activate(NSLayoutConstraint.constraints(withVisualFormat: "V:|-0-[player_one_view]-0-|", options: [], metrics: nil, views: views_dict))
        NSLayoutConstraint.activate(NSLayoutConstraint.constraints(withVisualFormat: "H:|-0-[player_one_view]-0-|", options: [], metrics: nil, views: views_dict))
        NSLayoutConstraint.activate(NSLayoutConstraint.constraints(withVisualFormat: "V:|-0-[player_two_view]-0-|", options: [], metrics: nil, views: views_dict))
        NSLayoutConstraint.activate(NSLayoutConstraint.constraints(withVisualFormat: "H:|-0-[player_two_view]-0-|", options: [], metrics: nil, views: views_dict))
```

4. Set each player view's url inside of the parent VC initializer (with a url from NextLevel funny enough)
```swift
    optionOnePlayer.setUrl(optionOneURL)
    optionTwoPlayer.setUrl(optionTwoURL)
```

5. Using lifecycle method overrides, configure the player vcs to be moved around:

```swift
    
    override func viewDidLoad() {
        self.addChildViewController(optionTwoPlayer)
        self.addChildViewController(optionOnePlayer)
        optionOnePlayer.didMove(toParentViewController: self)
        optionTwoPlayer.didMove(toParentViewController: self)
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        optionOnePlayer.playFromBeginning()
        optionTwoPlayer.playFromBeginning()
    }
```

I know how close I am because the result is the following:
<img width="554" alt="screen shot 2017-06-02 at 7 05 44 pm" src="https://cloud.githubusercontent.com/assets/7704414/26747831/8ad44e60-47c6-11e7-9057-dc80bb3b327b.png">

It loads the player views with a thumbnail, but does not play the video. I even hooked up the calls to `playFromBeginning()` to a button just to make sure they're being called. They are.

And one final note to make it more interesting.... the first time I ever ran the code, both videos played without issue. It has not worked a single time since.

Thanks for checking this out.

**Comment by thexande** [comment]
@piemonte any thoughts on this?

**Comment by piemonte** [comment]
hey @thexande nothing looks out of the ordinary to me. personally, i'd just get one player working first, then add in the second one. also try using the same source and verify that source works.

as long as you can verify both controllers are loaded using the debugger and they reach the ready state for their appropriate Url. hope that helps.

**Comment by thexande** [comment]
@piemonte perhaps there is some kind of a race condition because adding a delay to the `playFromBeginning()` call makes this work.
