### ISSUE TITLE
Can't compile sample app

### ISSUE THREAD

**Issue by krumjahn** [piemonte/Player#15]
When I compile and try to run the player app, it gives me a whole bunch of errors.

![screen shot 2015-04-16 at 2 41 45 pm](https://cloud.githubusercontent.com/assets/505516/7175414/eed5e1c0-e446-11e4-8162-ed99e2de0d66.png)

**Comment by piemonte** [comment]
@krumjahn the Swift 1.2 branch hasn't been merged into master. You can find that code here:

https://github.com/piemonte/Player/tree/xcode-6.3

**Comment by piemonte** [comment]
it looks like there are still a few bugs in Xcode 6.3 even on the branch. i'll fix/merge swift 1.2 changes sometime this afternoon.

**Comment by piemonte** [comment]
commit 5805c0de0c55e28f5221c8085244157f78fd6c6a
Merge: 7d70517 3d7433b
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Thu Apr 16 21:43:27 2015 -0700

    merge xcode-6.3, update to use Swift 1.2 initialization changes
