### ISSUE TITLE
Problem playing video with no domain and port

### ISSUE THREAD

**Issue by danieltigse** [piemonte/Player#154]
When I reproduce this URL:
https://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
Everything works fine

But When I try to reproduce this one
http://200.124.245.35:8000/media_anuncios/media_anuncios/Aguabajo12/agua12.mp4

Nothing happens

**Comment by piemonte** [comment]
hey @danieltigse thanks for interest in the library. the second URL doesn't work for me even on the desktop. maybe it needs https at the beginning?

**Comment by danieltigse** [comment]
It actually works @piemonte look:

![screen shot 2017-06-17 at 7 44 16 pm](https://user-images.githubusercontent.com/1870723/27257265-6cd9dde6-5395-11e7-9679-a3e81f1875ff.png)

**Comment by piemonte** [comment]
hey @danieltigse apologies, i was using safari to view. so player is a small wrapper around AVPlayer in conjunction with NSURL. if it isn't streaming properly, it's probably due to the constraints related to those classes.

**Comment by danieltigse** [comment]
Don't worry. Do you think is because the video URL doesn't have a domain? It is just the IP and the port.
