### ISSUE TITLE
Unable to install with carthage

### ISSUE THREAD

**Issue by Yetispapa** [piemonte/Player#155]
I would like to use your player in my app. I use carthage for the installation. Unfortunately I got the following error: 

*** Skipped building Player due to the error:
Dependency "Player" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/piemonte/Player/issues/new

This was my command:

`carthage update Player --platform iOS`

I saw a similar issue [here](https://github.com/piemonte/Player/issues/144)

Can someone give me an advice on this. Thank you

**Comment by swemoney** [comment]
Also experiencing this issue. Not familiar enough with creating Carthage frameworks so I'm not quite sure how to go about fixing this myself.

**Comment by swemoney** [comment]
I just submitted a pull request #157 that appears to resolve the Carthage issues. More testing is probably needed.
