### ISSUE TITLE
Cannot assign value type of 'UIViewController' to 'PlayerDelegate'

### ISSUE THREAD

**Issue by mrfarukturgut** [piemonte/Player#158]
I got the warning same in the title.  

<img width="807" alt="screen shot 2017-07-11 at 23 22 22" src="https://user-images.githubusercontent.com/6718272/28085141-0f479e9e-6690-11e7-8085-a34514b6befb.png">

And here is the code; 

```
import UIKit
import Player

let videoUrl = URL(fileURLWithPath: "")

class PreviewViewController: UIViewController {

    var player = Player()
    
    override func viewDidLoad() {
        super.viewDidLoad()

        self.player.playerDelegate = self
        
        // Do any additional setup after loading the view.
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.setNavigationBarHidden(true, animated: false)
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```
Am I doing something wrong or what? Because I get this error also with [NextLevel](https://github.com/NextLevel/NextLevel)

**Comment by piemonte** [comment]
hey @mrfarukturgut you're part way there. you need to implement the protocol in your class too:

https://github.com/piemonte/Player/blob/master/Project/Player/ViewController.swift#L99-L115

```swift
extension PreviewViewController: PlayerDelegate {
// playerDelegate methods...
}
```

it's setup this way, such that you're required to implement those methods.
