### ISSUE TITLE
Carthage install not working for v 0.7.0

### ISSUE THREAD

**Issue by JakubMazur** [piemonte/Player#160]
`carthage update --platform iOS`

returns an error: 

> Dependency "Player" has no shared framework schemes for any of the platforms: iOS
> 
> If you believe this to be an error, please file an issue with the maintainers at https://github.com/piemonte/Player/issues/new

**Comment by piemonte** [comment]
hey @JakubMazur i added a shared framework scheme last year, let me know if you still encounter issues. thanks again.
