### ISSUE TITLE
Make Standalone UIView Player instead of a UIViewController subclass

### ISSUE THREAD

**Issue by efremidze** [piemonte/Player#164]
I'm interested in making a UIView subclass of the Player, which isn't a subclass of a UIViewController. It would have the same functionality and features. Any interest in this?

**Comment by Isuru-Nanayakkara** [comment]
Yes!

**Comment by aziz92** [comment]
Yes! Need the same thing. I'm not sure what the idea was behind the use of UIViewController in this library.

**Comment by SarimAshfaq** [comment]
Not sure if it'll work for you but I've done a little enhancement. I've written custom class with activity indicator while buffering and mute/unmute button. So you don't have to write everything over and over and add them in storyboard. Please follow the link. and use **IPlayerView** class for your UIView
https://github.com/SarimAshfaq/IPlayerView

**Comment by piemonte** [comment]
in the latest version `0.9.1`, the PlayerView has been exposed as API too
