### ISSUE TITLE
add observer UIApplicationDidBecomeActive

### ISSUE THREAD

**Issue by PoeticPete** [piemonte/Player#166]
First I'd like to say that this is an awesome video player. One thing that would be nice is having the video player play automatically when the application becomes active (not just enters the foreground). Currently the video player will pause when the notification center is pulled down (UIApplicationWillResignActive), but to play it again the UIApplicationDidBecomeActive would have to be implemented. Let me know what you think :)

**Comment by piemonte** [comment]
this has been merged with: https://github.com/piemonte/Player/pull/169
