### ISSUE TITLE
Caching AVAssets

### ISSUE THREAD

**Issue by ghost** [piemonte/Player#17]
Hi again @piemonte,

What would be the best way for caching AVAssets for multiple Player instances, i.e. a tableview and in each cell holds a Player instance with a different URL path? I am striving for the same logic being done for images, like in many other image caching optimised examples and libraries specialised with images. I will probably use HanekeSwift or something that I have to build from the ground up. Probably I have to modify or customize the setupAsset function in Player, but I am not certain yet.

I am just curious what comes to your mind about this @piemonte?

**Comment by confile** [comment]
+1

**Comment by itsmeonline** [comment]
+1

**Comment by AncAinu** [comment]
+1

**Comment by gazialankus** [comment]
I'm doing this with a tableview using this branch at my fork: https://github.com/gazialankus/Player/tree/separating 
I separated the contents to a PlayerContents class. 

However, this line seems to happen a bit too early and sometimes I see the first frame of the previous video right after the video is loaded: 
https://github.com/gazialankus/Player/blob/separating/Sources/Player.swift#L665

I hide/show, remove/add Player, but I still see the first frame sometimes. 

Any input or help is appreciated to get rid of this "first frame" bug. Feel free to use this idea to separate assets from Player.

**Comment by danieldelouya** [comment]
+1

**Comment by piemonte** [comment]
had a big request for caching support, so may add in the coming weeks

**Comment by yunustek** [comment]
+1

**Comment by honga** [comment]
🙏 any updates on caching? @piemonte

**Comment by yunustek** [comment]
Can you check this repo? This has resolved the video cache:
https://github.com/wxxsw/GSPlayer

**Comment by piemonte** [comment]
@honga negotiations never finalized on the contract, unfortunately

**Comment by waterdrake** [comment]
+1 - Any updates on adding caching support?

Or, does anyone have any suggestions on how to implement your own version of video caching?
