### ISSUE TITLE
Video playing does not rotate when screen rotates

### ISSUE THREAD

**Issue by petersmax** [piemonte/Player#173]
Hello,

I have been tinkering with this in a few sample project(s) these last few days and suddenly yesterday, the video while in playback won't rotate and neither will the sample video demo from the project here. See the following for example: https://www.screencast.com/t/1kexAbQ1cFkn

I do not believe I have changed the orientations of the any of the ViewControllers from the VCs themselves and the project solution orientation and even tried it on another laptop that has never had XCode and the same result. Thoughts?

I have made sure to use 0.7.0 on Swift3.1

**Comment by 131e55** [comment]
Hello @petersmax😺

I think the topic is about UIView.
Player' sample project does not use both AutoLayout and AutoResizingMask.
How about using AutoResizingMask?

#### Example
```
self.player.playerDelegate = self
self.player.playbackDelegate = self
self.player.view.frame = self.view.bounds
self.player.view.autoresizingMask = [.flexibleWidth, .flexibleHeight] //❗

self.addChildViewController(self.player)
self.view.addSubview(self.player.view)
self.player.didMove(toParentViewController: self)
        
self.player.url = videoUrl        
```
