### ISSUE TITLE
Seek to time with tolerance method deprecated in iOS 11

### ISSUE THREAD

**Issue by dmzza** [piemonte/Player#174]
This method without a completion handler has been deprecated:
```swift
func seek(to time: CMTime, 
          toleranceBefore: CMTime, 
          toleranceAfter: CMTime)
```

In `AVPlayerItem`, Apple writes:
> Use `-seekToTime:toleranceBefore:toleranceAfter:completionHandler:`, passing `nil` for the `completionHandler` if you don't require notification of completion.

## Proposed Solution
Offer a new method on Player:
```swift
func seek(to time: CMTime, 
          toleranceBefore: CMTime, 
          toleranceAfter: CMTime, 
          completionHandler: ((Bool) -> Swift.Void)? = nil)
```

This would continue to support use of the method without a completion handler as well.

**Comment by piemonte** [comment]
commit cabf0893f0ac9ae89ec3d305a0a8d6a586bf37d8
Author: patrick piemonte <patrick.piemonte@gmail.com>
Date:   Wed Sep 27 23:17:37 2017 -0700

    Player, remove deprecated API (via dmzza)
    
    https://github.com/piemonte/Player/pull/175
