### ISSUE TITLE
How can I revise it for macOS app?

### ISSUE THREAD

**Issue by chaocharleswang** [piemonte/Player#177]
How can I revise it for macOS app?

Thanks!

**Comment by chaocharleswang** [comment]
When I convert it into mac app, I have the following issue (in UIView -> NSView):

override class var layerClass: AnyClass {
        get {
            return AVPlayerLayer.self
        }
    }

How can I solve it for NSView? Thanks!

**Comment by chaocharleswang** [comment]
I found the following document:
https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CoreAnimation_guide/SettingUpLayerObjects/SettingUpLayerObjects.html

I think I need do some change for makeBackingLayer() of NSView.

**Comment by piemonte** [comment]
hey @chaocharleswang that's outside of the scope for me personally, but feel free to create a PR if you'd like to help add support that functionality.
