### ISSUE TITLE
How to save the video to camera roll?

### ISSUE THREAD

**Issue by capitan91** [piemonte/Player#179]
How to save the video to camera roll?

Thank you!

**Comment by piemonte** [comment]
hey @capitan91, this library is primarily for streaming video or playing files that exist locally.

if you'd like to save the file that locally exits, there's examples within the project here:

https://github.com/NextLevel/NextLevel

If you'd like to save a remote file, you'll have to download it separately, maybe multipart data request via https://github.com/Alamofire/Alamofire/ and then storing it.
