### ISSUE TITLE
Improvements: fillMode as Enums

### ISSUE THREAD

**Issue by confile** [piemonte/Player#18]
It is hard to find which fill modes are supported when they are as strings. 

```
self.player.fillMode = “AVLayerVideoGravityResizeAspect”
```

Could you please add the possible fill modes to the documentation or make them available with an enum?

**Comment by piemonte** [comment]
hey @confile that's a nice idea.

**Comment by confile** [comment]
@piemonte Player is a really great lib. Thanks for sharing. 
Are there any other fillModes supported right now. Like aspect fill?

**Comment by vbergae** [comment]
(I know it's a bit old, but may help)

@confile AVFoundation defines 3 constants:

`AVLayerVideoGravityResizeAspect`
`AVLayerVideoGravityResizeAspectFill`
`AVLayerVideoGravityResize`

More Info: https://developer.apple.com/library/prerelease/ios/documentation/AVFoundation/Reference/AVFoundation_Constants/index.html#//apple_ref/doc/constant_group/Video_Gravity

**Comment by Matthewspear** [comment]
@piemonte Has this been implemented? I'd like to jump into open source and this seems a simple enough addition.

**Comment by piemonte** [comment]
hey @Matthewspear thanks for checking in. i'm swamped with some other things so feel free to submit a PR. contributions are always welcome. ✌️

**Comment by Matthewspear** [comment]
Quite new to submitting to OS projects - How does this look?
I took inspiration from the way a UIImageView handles content mode:

```swift
public enum FillMode: String
{
    case resize = "AVLayerVideoGravityResize"
    case resizeAspectFill = "AVLayerVideoGravityResizeAspectFill"
    case resizeAspectFit = "AVLayerVideoGravityResizeAspect"
}
```

one other alternative would be to just use ```resize, aspect, aspectFill```, which would you prefer?

Can make a pull request once happy with preference or have any other ideas!

Matt

**Comment by piemonte** [comment]
Hey @Matthewspear apologies, i didn't see your last comment. The way you have it is great, I'll just paste it into the class and give you props in the comment.

Making pull requests for OS just takes a couple clicks. Create a fork of the project you want to modify, then push you modification to your fork. After that github has an interface that allows you to create the pull request itself. From there it can get review/merged. Best of luck.

📎  https://help.github.com/articles/creating-a-pull-request/

**Comment by Matthewspear** [comment]
👍
