### ISSUE TITLE
Why not using a enum for fillMode attribute?

### ISSUE THREAD

**Issue by lm2343635** [piemonte/Player#185]
I mean it is more convenient to set the fillMode like
```Swift 
player.fillMode = .resizeAspectFill
```
rather than
```Swift
player.fillMode = PlayerFillMode.resizeAspectFill.avFoundationType
```

**Comment by piemonte** [comment]
hey @lm2343635, there's a few pull requests i need to review that will improve upon this.

just a simple wrapper that should probably just be a typealias instead. you can call it legacy code.

**Comment by piemonte** [comment]
📎 95619d9ec48417ad9e736fb446b23d40f2508db0

**Comment by lm2343635** [comment]
Thanks! @piemonte
