### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by vasylboy90** [piemonte/Player#186]
I used this player on my app. And Video is playing well.
But When i play video serveral times, video player is freeze and memory is much increased.

I debugged memory on Xcode. I found when i play video with this player, memory is increasing at least 2~3 MB. i could also 5MB too.

This is code part that i used.

deinit {
        self.player.willMove(toParentViewController: self)
        self.player.view.removeFromSuperview()
        self.player.removeFromParentViewController()
    }

override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
        self.player.muted = true
        self.player.playerDelegate = self
        self.player.playbackDelegate = self
        self.player.view.frame = self.playerContView.bounds
        self.player.fillMode = PlayerFillMode.resizeAspectFill.avFoundationType
        self.addChildViewController(self.player)
        self.playerContView.addSubview(self.player.view)
        self.player.didMove(toParentViewController: self)
        self.player.playbackLoops = true
    } 

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.player.url = videoUrl
        self.player.playFromBeginning()
    }

Looking forward to see any reply.
Thanks
Vasyl

**Comment by piemonte** [comment]
hey @vasylboy90 thanks for interest in the project. last week, i published a couple new versions of the library. (0.9.1)

if you could update to those and let me know if you see the same behavior, that would help.

**Comment by sc0rch** [comment]
> If we're talking about NSNotification, that is often how you get a retain cycle. The notification center retains the observer until you unregister it. You thus cannot get deinit until after the observer has been removed. Therefore, you cannot remove the observer in deinit.
source: https://stackoverflow.com/questions/41772225/explanation-for-deinit-not-called?rq=1

I moved deinit-stuff to releasePlayer function and called it manually as workaround.
And memory issue is gone now.

**Comment by piemonte** [comment]
thanks @sc0rch! i appreciate the note. i hadn't encountered this issue in my projects, then after looking into it from your note, realized i was retaining references to self in all of the observer blocks. (sorry!! ☺️)

here's a patch.
