### ISSUE TITLE
no volume if unmuted video played when device on silent

### ISSUE THREAD

**Issue by simran-lbbd** [piemonte/Player#192]
im unable to play the audio when the device is silent - can only hear when the device has ringer on, is there something i'm missing?

**Comment by kamrankhan07** [comment]
https://stackoverflow.com/questions/35289918/play-audio-when-device-in-silent-mode-ios-swift
has to be fixed.

**Comment by piemonte** [comment]
[before playing](https://github.com/piemonte/Player/issues/192#issuecomment-420883897)

```swift
try? AVAudioSession.sharedInstance().setCategory(.playback, mode: .default, options: [])
```
