### ISSUE TITLE
Playback stalls after playing video in loop for 2 times

### ISSUE THREAD

**Issue by kamrankhan07** [piemonte/Player#193]
Player stalls for no reason after looping video 2 times. I added a short HLS video to test, and almost every time it stops after playing it twice. Did anybody ever faced the same issue?

**Comment by j0rdsta** [comment]
I'm also encountering this issue! I'm passing a remote m3u8 file to Player and while it plays twice, it won't loop or allow you to resume after that.

**Comment by kamrankhan07** [comment]
I am not sure what was causing the issue, may be some internal flags. I paused the video before seeking to start and play again, and it seems to work fine now. 
@piemonte please merge this.
