### ISSUE TITLE
Issue Playing Local Files

### ISSUE THREAD

**Issue by efbsecond** [piemonte/Player#195]
Hi, Love the Library - Just having a confusing issue - I am also using your NextLevel Camera Library and Player will not display the merged or exported local clips (This also seems to be the case for other local files.) The Implementation is fine, as I have checked that both Player can display remote URL's in the view and that a standard AVPlayer can play the problematic local files. Just curious if this is a known bug or If I am missing something?

Thanks

**Comment by piemonte** [comment]
hey @efbsecond, thanks for the project interest. ✌️ 

can you verify that `Player` can play a local file from the default camera app? i haven't heard anyone having this issue, so it's possible that there's some type of nuance with the local file path provided.

**Comment by efbsecond** [comment]
Thanks for the response @piemonte

Went and did a thorough check - `Player` could not play any of the selected local files from the default camera app, while a basic AVPlayer I ran up was able to play from the same URLs/Assets and Implementation.

**Comment by piemonte** [comment]
@efbsecond when you make the URL, you should be using this class func for local files:

```swift
    public init(fileURLWithPath path: String)
```

**Comment by efbsecond** [comment]
@piemonte Interesting Development - I confirmed that I was  following the above, and it did not fix the problem. The only way I have been able to get the player to play local files is to go to from the player screen, exit to home and re open the app (same behavior with lock/unlock) at the player screen. Also randomly it played once after I removed a configuration to mute the player (this is non replicable behavior however while the home-> reopen pattern is.) Digging through the player I see that these Became Active and Foreground notifications trigger a `play()` -- bearing this in mind I was curious if anything came to mind for you associated with this confluence of Local Assets and failing initial play invocations. If not, no worries and Thanks again for your work and support on this library

**Comment by Chepond** [comment]
@piemonte 
I found the problem of playing videos from PHAsset, its caused by the format, .3pg, as all my .mp4 are working well on this thanks. Just the player(_ player: Player, didFailWithError error: Error?) didnt trigger.. will this be called when unsupported files are set to the player?



but for this problem:
init the player object by setting the url and add subview to my view
it normally works, but sometimes it doesnt load at all, i checked the url by init it on Data, and it shows bytes, and also when the player doesnt show any video, PlayerDelegate, playerReady(_ player: Player) never call.
the url was actually from NextLevel, NextLevelClip.url, can i just the URL directly or i have to use it through public init(fileURLWithPath path: String),
I can actually hear audio of the clip, but the video never appear..

many thanks

**Comment by Chepond** [comment]
@piemonte 
I have uploaded two screenshot of my related issue, as both url succeed to be read by the video range slider bar, but the player sometimes could not read the video from url, playerReady(_ player: Player)  never called. but the audio is fine when i try to play it, it actually has sound
![screen shot 2018-09-17 at 5 05 57 pm](https://user-images.githubusercontent.com/30211691/45614432-197bac00-ba9c-11e8-9eac-ee0a719a7b7a.png)
![screen shot 2018-09-17 at 5 05 38 pm](https://user-images.githubusercontent.com/30211691/45614434-1b456f80-ba9c-11e8-825c-508fc1fdc5b4.png)

**Comment by mustafakayya** [comment]
I have same problem with @Chepond

**Comment by Chepond** [comment]
@piemonte 
Player Object seems never deinit the AVPlayer Object, and when it accumulates to around 16 AVPlayer Object, the app will fail to use any AVFoundation related functions.
There is a problem that when I present my custom view controller(init a new one every time)
There is a Player variable in my custom view controller
var player:Player?

then I init  the player when I play the video. But when viewWillDisappear, I set the player = nil, also the breakpoint I have set in the deinit{} of Player.swift never gets hit. Below code is how init the Player Object, added comments to explain.

self.player = Player()
            if let player = self.player {

                player.playerView.backgroundColor = UIColor.red
 /* I set this to check if the view actually appear, but it doesnt show anything red, even I inspect it in xcode, there is nth shown for the player.playerView, PlayerDelegate, playerReady(_ player: Player) also never gets hit, player.playerView.isReadyForDisplay is always false, this happens randomly and quite frequent, I am also using URL.init(fileURLWithPath path: String) by converting NextLevelClip.url to String and back to URL, but seems not effective*/

                player.playbackResumesWhenBecameActive = false
                player.playbackResumesWhenEnteringForeground = false
                player.fillMode = PlayerFillMode.resize
                player.playerDelegate = self
                player.playbackDelegate = self
                player.url = url
                if let playerView = player.view {
                    self.vPlayer.addSubview(playerView)
                    player.fillMode = PlayerFillMode.resizeAspect
                    playerView.translatesAutoresizingMaskIntoConstraints = false
                    let topConstraint = NSLayoutConstraint(item: playerView, attribute: .top, relatedBy: .equal, toItem: self.vPlayer, attribute: .top, multiplier: 1, constant: 0)
                    let bottomConstraint = NSLayoutConstraint(item: playerView, attribute: .bottom, relatedBy: .equal, toItem: self.vPlayer, attribute: .bottom, multiplier: 1, constant: 0)
                    let leadingConstraint = NSLayoutConstraint(item: playerView, attribute: .leading, relatedBy: .equal, toItem: self.vPlayer, attribute: .leading, multiplier: 1, constant: 0)
                    let trailingConstraint = NSLayoutConstraint(item: playerView, attribute: .trailing, relatedBy: .equal, toItem: self.vPlayer, attribute: .trailing, multiplier: 1, constant: 0)
                    self.view.addConstraints([topConstraint, bottomConstraint, leadingConstraint, trailingConstraint])
                }
            }

**Comment by quangctkm9207** [comment]
+1

**Comment by chris-redbeed** [comment]
I got the same issues since iOS 12 - before that everything was fine.
But i am not sure if i update the Player with a newer version and that's create the problem.

**Comment by piemonte** [comment]
i'm integrating this into a new project over the next couple weeks, will finally get a chance to look into it. bummer to hear and appreciate the comments!

**Comment by piemonte** [comment]
:paper https://github.com/piemonte/Player/issues/199

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/Player/issues/199
