### ISSUE TITLE
Could not see video, sound only!

### ISSUE THREAD

**Issue by danhhgl** [piemonte/Player#199]
I have a problem when using Player library. I use the code below and it works success only once time. If I run the app again, I could not see the video, just sound playing. What's wrong? I'm using Xcode 10. Can anyone help me? Thank you in advance!!!

```
class ViewController: UIViewController {
    
    var player: Player!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.player = Player()
        self.player.playerDelegate = self
        self.player.playbackDelegate = self
        self.player.view.frame = self.view.frame
        
        print("player: \(self.player.view.frame)")
        
        self.addChild(self.player)
        self.view.addSubview(self.player.view)
        self.player.didMove(toParent: self)
        
        let url = Bundle.main.url(forResource: "tiktok", withExtension: "mp4")
        
        self.player.url = url
    }
}
```

<img width="874" alt="screen shot 2018-10-09 at 8 17 08 am" src="https://user-images.githubusercontent.com/19302957/46641422-bf9e6b80-cb9b-11e8-8e3d-655490f8161b.png">

**Comment by piemonte** [comment]
thanks, i have a fix for this

**Comment by danhhgl** [comment]
Great! It's working. Thank you so much!!! 👍

**Comment by xthaohg** [comment]
I have this problem. Player not show in the first open app. But I open this player again. I see it. But I using simulator. I don't see it

**Comment by xthaohg** [comment]
And I using zfplayer for other view. I think it conflic your player
