### ISSUE TITLE
Using player inside a custom TableViewCell

### ISSUE THREAD

**Issue by uguryavas** [piemonte/player#2]
Hey Patrick. First things first, thanks for an awesome library, really =)

Basically, I am trying to implement a Vine-like app which will have a video player inside each cell and other buttons for likes, sharing et cetera. What is your opinion about this and do you think that is this possible with the current design of the library itself?

**Comment by piemonte** [comment]
hey @uguryavas thanks for the interest in the library. player can be used in "Vine-like" table view cells.

if you're not already familiar, you just need to think about supporting cell re-use, i recommend reallocating the player controller and resetting the cell back to the original thumbnail.

it's possible for you to try using the same player controller instances and "resetting" them when re-use occurs, as oppose to reallocating the controller, but i can't remember if there were any bugs in doing so. by reset, i just mean that you're moving the time back to zero and providing the asset URL over again. I recommend probably just re-allocating.

i've had friends ask me about some type of stream caching, so that the videos play faster but i haven't had a need to get into that optimization.

**Comment by ingouackaz** [comment]
Hi @piemonte , what do you mean by " moving the time back to zero " ?

Which method should i called ?

**Comment by piemonte** [comment]
@ingouackaz hi there. in your prepareCellForReuse or similar method, just set the URL again and it should reset the player

**Comment by rromanchuk** [comment]
@piemonte i'm actually implementing this now, it's working actually quite well without having to instantiate the controller every load. The only problem is it's a little bit tricky properly cleaning up the cell.  I think it would be nice either add a convenience method, or allow for a `path` to be passed nil which indicates a reset state. 

Maybe a convenience method like `prepareForReuse()` that 
1. Stops playback
2. Rewinds playback
3. Hides the preview

Right now i'm reaching into the class to do all of these cleanup methods. 

But just a note for others trying to do this, `prepareForReuse` is just for resetting the cell, but it's up to the implement  cells that may be long living. When a cell goes off screen you need to utilize techniques like `tableView(_:didEndDisplayingCell:forRowAtIndexPath:)`   I also wouldn't recommend setting any data in `prepareForReuse` as it's  `tableView(_:cellForRowAtIndexPath:)` responsibility, you may be working with stale data.

**Comment by ingouackaz** [comment]
Hi @rromanchuk  !

I've just realised that many people have the same issue as me.
http://stackoverflow.com/questions/17617066/avplayer-plays-on-simulator-but-doesnt-on-a-real-device

It works perfectly on the simulator, but it doesnt on the device.

@piemonte  any idea ?

**Comment by piemonte** [comment]
@rromanchuk awesome ideas. we can put a little extension on there that provides that func. i can probably add it this evening or sometime tomorrow. :v:

**Comment by piemonte** [comment]
@ingouackaz not sure what you're encountering, if you can reproduce that problem with the `Player` sample project, please create an issue with a gist of the changes that trigger it. thanks for the proj interest.

**Comment by rromanchuk** [comment]
@piemonte i can submit a UITable/CollectionView example too. I had to hack a bit of the player to add this 'reset' method  because a lot of things are are managed in init/deinit so a bit tricky to keep it DRY


```swift
    public func sharedSetup() {
        self.playerView.playerLayer.hidden = true
        self.playerView.playerLayer.addObserver(self, forKeyPath: PlayerReadyForDisplay, options: (NSKeyValueObservingOptions.New | NSKeyValueObservingOptions.Old), context: &PlayerLayerObserverContext)

        NSNotificationCenter.defaultCenter().addObserver(self, selector: "applicationWillResignActive:", name: UIApplicationWillResignActiveNotification, object: UIApplication.sharedApplication())
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "applicationDidEnterBackground:", name: UIApplicationDidEnterBackgroundNotification, object: UIApplication.sharedApplication())
    }

    private func sharedDeinit() {
        NSNotificationCenter.defaultCenter().removeObserver(self)
        self.playerView.layer.removeObserver(self, forKeyPath: PlayerReadyForDisplay, context: &PlayerLayerObserverContext)
        self.player.pause()
        self.setupPlayerItem(nil)
    }

    public func reset() {

        sharedDeinit()
        sharedSetup()
    }
```

**Comment by ingouackaz** [comment]
I have almost fixed it !

@rromanchuk , @piemonte , do you know , how i can add or remove the bottom layer in AVPLayerViewController wich contains the play controls,  the progress bar,and the fullscreen button ?

![image](https://cloud.githubusercontent.com/assets/3285421/6636957/2d845bdc-c975-11e4-9ddb-5a08c2f0b128.png)

Thank you !

**Comment by sentiasa** [comment]
Hi @rromanchuk, if you made Player work for the TableViews, can you please write a mini-guide on how to achieve that? Should I put the code you shared above in my Player.swift, and then call `reset()` on TableViewController's `cellForRowAtIndexPath`? How should I exactly apply this approach in the TableViewController and TableViewCell? I'd be very happy if you can help. Thanks
