### ISSUE TITLE
Setup own AVPlayerItem in Player.framework

### ISSUE THREAD

**Issue by romanmiller** [piemonte/Player#200]
Hi
I fork your framework and want to setup own AVPlayerItem to this Player.framework.
I want to set AVPlayerItem out of framework as a property, and then Player.framework take this AVPlayerItem object and set to current AVPlayer.

**Comment by piemonte** [comment]
hey @romanmiller nice request. i think i'll be adding something along these lines for caching support.

📎 https://github.com/piemonte/Player/issues/17
