### ISSUE TITLE
Camera session and player recording doesn't working Together

### ISSUE THREAD

**Issue by lata-nga** [piemonte/Player#202]
I have added Player controller to our view hierarchy. Implemented all its delegate methods. If I use Player version 0.9 everything works fine but as soon as I migrate to Player 0.12, Player controller doesn't works. We can get the recorded video path(URL) after recording the video successfully but the player becomes nil for most of the time and doesn't display the recorded video.

**Comment by piemonte** [comment]
hey @lata-nga thanks for project interest!

can you verify that you're using version `0.12.1`

there was a bug in that point release that should address your issue:

042f01f43d162b21f49fde7892896d90b4053fd7
