### ISSUE TITLE
Feature Request - Play video in reverse

### ISSUE THREAD

**Issue by otymartin** [piemonte/Player#203]
@piemonte 

I would like to be able to play a video in reverse (from end to beginning). 

Also loop its playback infinitely eg. (Play from beginning to end **THEN** reversed(end to beginning) Looped forever.

I've been following this tutorial to achieve it on my own but would love for the library to officially support it.
https://swift.unicorn.tv/articles/avfoundation-to-play-and-reverse-video

**Comment by piemonte** [comment]
hey @otymartin thanks for the request but i don't think i'll be adding support for this anytime.
