### ISSUE TITLE
Example using Player in reusable cell

### ISSUE THREAD

**Issue by patthehuman** [piemonte/Player#210]
We are using Player to play video inside a collectionview with cells that are full screen.

Is there an example on how to properly use Player inside a reusable cell?

**Comment by SerxhioGugo** [comment]
I would like to see this too!

**Comment by PahlevanyanSamvel** [comment]
I suggest you use the container view inside the collection view cell.
for example`
`cell.container.addSubview(self.player.view) `

**Comment by AppleTTT** [comment]
I would like to see this too

**Comment by andrewfashion** [comment]
Following up on this.

**Comment by andrewfashion** [comment]
Would love to see this as well! Thank you!
