### ISSUE TITLE
bufferingState == .ready

### ISSUE THREAD

**Issue by TheHmmka** [piemonte/Player#213]
Hi there!
I figured out one issue with state of buffer.
As I see you set up state in next place of code:

```
self._playerItemObservers.append(playerItem.observe(\.loadedTimeRanges, options: [.new, .old]) { [weak self] (object, change) in
            guard let strongSelf = self else {
                return
            }

            strongSelf.bufferingState = .ready
```

But you don't need to do this here cause now playerBufferingStateDidChange callback is calling before the video should play. You just need to comment or delete this line of code and everything will be nice!

Thanks you!

**Comment by piemonte** [comment]
@TheHmmka thanks much, are you saying that `isPlaybackLikelyToKeepUp` sets the state to Ready?

**Comment by TheHmmka** [comment]
> @TheHmmka thanks much, are you saying that `isPlaybackLikelyToKeepUp` sets the state to Ready?

I mean, that isPlaybackLikelyToKeepUp is the right place to set bufferingState = .ready (as it implemented) and loadedTimeRanges is NOT right place (need to be deleted).

Thank you!
