### ISSUE TITLE
Aspect ratio not working on iOS 14 beta 6

### ISSUE THREAD

**Issue by MartinMoizard** [piemonte/Player#229]
I recorded a video with my phone and tried to play it with a `fillMode = .resizeAspect`.

Here is the result (using the demo app on master):
<img src="https://user-images.githubusercontent.com/395477/91333837-6a3ec800-e7ce-11ea-89e7-eec29261bf96.PNG" width=320 />

The aspect ratio is not working, here is how the video actually looks like:
<img src="https://user-images.githubusercontent.com/395477/91334105-c6a1e780-e7ce-11ea-9d0b-5b1618b74c1c.PNG" width=320 />

If needed, here is a link to the video I used: https://www.dropbox.com/s/l5x2nx07wrsnk7h/IMG_0016.MOV?dl=0

Any idea what might be the issue? I also tried to play the video after getting a `PHAsset` reference through the Photos API: same result.

Thanks a lot

**Comment by MartinMoizard** [comment]
For information, I tried playing the same video using a basic `AVPlayer`, and the aspect ratio worked like suposed.

**Comment by piemonte** [comment]
@MartinMoizard thanks will check it out
