### ISSUE TITLE
iOS 14 problem with portrait video

### ISSUE THREAD

**Issue by lafalex** [piemonte/Player#231]
Hello,

Since iOS14, videos in portrait are displayed like landscape video. The video ratio are not correct..
I tested the same video with AVPlayer directly, and it works.

For exemple this video:
https://d3u7oqnt1damfd.cloudfront.net/up/inside-e5286015-ee41-44cf-aba6-fca1cba84a20_69ec15ef-ea09-48f1-8e03-c19da89a4cea.mp4

**Comment by lafalex** [comment]
If we add `self._playerView.player = self._avplayer` in viewDidLoad function, seems to fix the problem...

**Comment by piemonte** [comment]
thanks @lafalex will update it
