### ISSUE TITLE
Support subtitle

### ISSUE THREAD

**Issue by anphunl** [piemonte/Player#25]
Can it display subtitle when playing? (SRT and ASS)

**Comment by piemonte** [comment]
hi there, that currently isn't feature in the library but a nice idea. feel free to contribute the functionality with a pull request.

**Comment by a-radwan** [comment]
Does it supports VTT subtitles formats

**Comment by majeedyaseen** [comment]
Does it support subtitles now ??
@piemonte

**Comment by piemonte** [comment]
no one has contributed support for subtitles, PR's welcome.
