### ISSUE TITLE
I set the rate for AVPlayer, it always fails. The reason for the failure is that it keeps calling 【 self._avplayer. play() 】

### ISSUE THREAD

**Issue by dosedo** [piemonte/Player#254]
` if (passedTime >= strongSelf.bufferSizeInSeconds ||
                strongSelf._lastBufferTime == strongSelf.maximumDuration ||
                timeRanges.first == nil) &&
                strongSelf.playbackState == .playing {
                strongSelf.play()
            }
`

When playing an HTTP video, always call ：【strongSelf. play()】
That is to say, it will always be called：【self._avplayer.play()】

I'm not sure if this logic is correct.

But when I set the rate for AVPlayer, it always fails.

The reason for the failure is that it keeps calling 【 self._avplayer. play() 】

My testing environment is：
iOS 16.7.2  
XCode 15.0.1  
The latest Player.swift

http link:
let mp4Url = "https://vd3.bdstatic.com/mda-phv1zugg2n3c8n4n/720p/h264/1693358819109409657/mda-phv1zugg2n3c8n4n.mp4?v_from_s=hkapp-haokan-hbe&auth_key=1693663538-0-0-533e7ed71380a893120cc0762bf2b3a0&bcevod_channel=searchbox_feed&cr=2&cd=0&pd=1&pt=3&logid=0338572677&vid=4140107770816422827&klogid=0338572677&abtest=112751_3"

**Comment by piemonte** [comment]
https://github.com/piemonte/Player/issues/253
