### ISSUE TITLE
Push latest version to CocoaPods Trunk

### ISSUE THREAD

**Issue by xhacker** [piemonte/Player#28]
Currently it will install 0.0.5.

**Comment by misslester** [comment]
- Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/d639038141fa90ce64c3543da5f8cddfa5ce75c5/Specs/Player/0.0.6/Player.podspec.json
  - Log messages:
    - August 5th, 22:16: Push for `Player 0.0.6' initiated.
    - August 5th, 22:16: Push for `Player 0.0.6' has been pushed (3.254268086
    s).
