### ISSUE TITLE
How to set full screen player when rotate device ? Thx for support

### ISSUE THREAD

**Issue by paneaktae** [piemonte/Player#29]
How to set full screen player when rotate device ? Thx for support

And How to get current time item player

**Comment by mdaymond** [comment]
+1

**Comment by piemonte** [comment]
just ensure you're resizing the view on rotation and the video playback is set to aspectratio fit, that's about it

**Comment by petersmax** [comment]
Hello,

I have been tinkering with this in a few sample project(s) these last few days and suddenly yesterday, the video while in playback won't rotate and neither will the sample video demo from the project here. See the following for example: https://www.screencast.com/t/1kexAbQ1cFkn

I do not believe I have changed the orientations of the any of the ViewControllers from the VCs themselves and the project solution orientation and even tried it on another laptop that has never had XCode and the same result. Thoughts?
