### ISSUE TITLE
Ability to resume video when the view is visible

### ISSUE THREAD

**Issue by xhacker** [piemonte/Player#31]
I found some code here https://github.com/piemonte/Player/blob/master/Source/Player.swift#L239-L245 to pause the video in `viewDidDisappear`. Is there any way to resume the video when the view is visible again?

**Comment by davidlondono** [comment]
there should be a switch to set if it shoud resume after the view appears again, it happens because you lose control of the view controller

**Comment by AntonReality** [comment]
@piemonte Is this solved? i don't see any related code in #63 pull request. It works ok for didEnterForeground, but it's not resuming video if view just disappear.

**Comment by piemonte** [comment]
hey @AntonReality, at one point in time i added these properties to control this behavior, if something is not as expected, let me know.

https://github.com/piemonte/Player/blob/master/Sources/Player.swift#L159-L163

**Comment by AntonReality** [comment]
@piemonte Thanks for a quick reply!
Yes, i've seen this,  but this is working only on application enter background/foreground, not the viewDidAppear. You have to override viewDidAppear for this.
