### ISSUE TITLE
Unable to build framework with Carthage: Dependency "Player" has no shared framework schemes

### ISSUE THREAD

**Issue by foreignfilm** [piemonte/Player#33]
Carthage version 0.8.0, attempting to install Player 0.0.6, on OS X 10.10.5:

```
Dependency "Player" has no shared framework schemes
```

**Comment by Comver** [comment]
same issue

**Comment by rromanchuk** [comment]
Can confirm with `carthage build --no-skip-current` The schemes are shared, but it looks like carthage doesn't like our project structure, or most likely a minor framework configuration error. I'll send a PR up this week. I may have to reorg the `Player.xcodeproj` but I have to dig into latest carthage development to track down what is actually going on.

**Comment by sapnix** [comment]
Issue still persists
`*** Checking out Player at "0.1.0"
*** Skipped building Player due to the error:
Dependency "Player" has no shared framework schemes`

**Comment by vittoriom** [comment]
Same here :(

**Comment by diejmon** [comment]
This library isn't Carthage compatible as it doesn't have Framework target at all.

**Comment by sapnix** [comment]
Well readme file says it is compatible with Carthage and even provides install instructions

**Comment by diejmon** [comment]
May be it used to work one day. No idea.

**Comment by piemonte** [comment]
ah yeah, it looks like the framework target got removed at some point, we should add it back in. apologies!

**Comment by sirvon** [comment]
this is still happening...any direction to move past this issue?

**Comment by piemonte** [comment]
hey @sirvon thanks for checking in. i haven't had a chance to add this myself, will try to in a week or so.

until then, feel free to either copy the Player.swift file into your project. You could even fork and add a framework target yourself which fixes the issue too. would be a nice PR. ✌️

**Comment by piemonte** [comment]
@sirvon added back in support, let me know if encounter an issue 👍

**Comment by piemonte** [comment]
commit ea793c7c6f207824ada396f26ff46fbc43c7a15f
Author: patrick piemonte <piemonte@alumni.cmu.edu>
Date:   Thu Dec 15 19:07:22 2016 -0800

    Project file update for Xcode 8.2
