### ISSUE TITLE
Huge problems to import

### ISSUE THREAD

**Issue by ppamorim** [piemonte/Player#35]
Hi.
I noticed a huge problems with this library, then, I can`t use it.
![captura de tela 2015-09-30 as 15 08 57](https://cloud.githubusercontent.com/assets/5521682/10202005/3683b92c-6785-11e5-9c97-bcf027f4e566.png)

**Comment by xhacker** [comment]
Are you using Swift 2.0? If so please use the `swift2.0` branch.

**Comment by ppamorim** [comment]
I`m using the swift 2 branch

**Comment by xhacker** [comment]
Can you try:
```
pod 'Player', :git => 'https://github.com/piemonte/Player.git', :tag => '0.7'
```

`0.6` is not Swift 2.0 ready.

**Comment by ppamorim** [comment]
Please add this on the readme.

**Comment by xhacker** [comment]
@ppamorim 0.0.7 pushed to CocoaPods, you should be able to install without specifying tag now.
