### ISSUE TITLE
Push 0.0.7 to CocoaPods Trunk

### ISSUE THREAD

**Issue by xhacker** [piemonte/Player#36]
I’ve merged `swift2.0` branch into master, and tagged the 0.0.7 version. @piemonte can you push the spec to CocoaPods? I don’t have the permission.

**Comment by misslester** [comment]
:+1:

**Comment by misslester** [comment]
CocoaPods 0.39.0.beta.5 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/2799737adccbe135cee14a1a76fb167795812c32/Specs/Player/0.0.7/Player.podspec.json
  - Log messages:
    - October 1st, 22:13: Push for `Player 0.0.7' initiated.
    - October 1st, 22:13: Push for `Player 0.0.7' has been pushed (1.55755948 s).

**Comment by xhacker** [comment]
Awesome thanks!

**Comment by piemonte** [comment]
thanks @xhacker :watermelon: 

thanks @misslester
