### ISSUE TITLE
can i consider the delegate methods as optional? 

### ISSUE THREAD

**Issue by rafaelmnz** [piemonte/Player#39]
The delegate methods are optional?

**Comment by piemonte** [comment]
it depends on how you use and integrate the player. you don't have to use delegation, if you don't want to but various state changes won't propagate.

**Comment by individual11** [comment]
I changed the code a bit to make them optional like below. Can do a pull request if you want?

```
@objc public protocol PlayerDelegate: class {
    optional func playerReady(player: VideoPlayerViewController) -> ()
    optional func playerPlaybackStateDidChange(player: VideoPlayerViewController) -> ()
    optional func playerBufferingStateDidChange(player: VideoPlayerViewController) -> ()
    
    optional func playerPlaybackWillStartFromBeginning(player: VideoPlayerViewController) -> ()
    optional func playerPlaybackDidEnd(player: VideoPlayerViewController) -> ()
}
```
If you change the code to above, you will see about 14 errors in the class where the delegate methods, when called, need to have a '?' to define them as optional.
