### ISSUE TITLE
Most efficient way to play a queue of videos?

### ISSUE THREAD

**Issue by switz** [piemonte/Player#4]
Is it possible to play the videos without a gap? Also, how can I minimize memory consumption by reusing the player?

```
    func playVideo() {
        videoPlayerController.videoPath = self.videoPath;
        
        // present
        self.addChildViewController(videoPlayerController);
        playerView.addSubview(videoPlayerController.view);
        videoPlayerController.didMoveToParentViewController(self);

        // Start Video
        videoPlayerController.playFromBeginning();
        //videoPlayerController.playbackLoops = true;
    }

    func videoPlayerPlaybackDidEnd(videoPlayer: PBJVideoPlayerController!) {
        videoPlayerController.removeFromParentViewController()
        videoPlayerController.view.removeFromSuperview()
        
        // setup next video and call self.playVideo()
    }
```

This might be of some interest: https://github.com/katokichisoft/SimpleGaplessPlayer

**Comment by switz** [comment]
I implemented two video players, A and B. I load B as soon as A starts playing (and vice versa) for the next video. I have a timer and when the video gets very close to the end, I swap the two views. This works fairly well, but it's not a seamless transition.

**Comment by piemonte** [comment]
hey @switz thanks for the feedback. based on the `player` design, it's one-to-one, one video and one player. i can keep this issue open for adding seamless playing for the future.

as for your handling of the two videos, that sounds fine, you can make the transition feel seamless but that's as good as it gets for now.

**Comment by freak4pc** [comment]
@piemonte @switz Sorry for bumping this but I'm in a similar issue ATM.

How come setting the "path" to a different one works (after the video ends playback)? 

I'm doing something like this

    func playerPlaybackStateDidChange(player: Player) {
        println("State changed to \(player.playbackState)")
        if player.playbackState == PlaybackState.Stopped{
            println("Changing url")
            x.path = "http://my.server.net/tests/vid00010.mp4"
        }
    }

But this crashes with 

```
2015-03-04 12:25:51.775 Vidback[50173:9031097] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7ff97295ba00 of class AVPlayerItem was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7ff971475f00> (
<NSKeyValueObservance 0x7ff97295c1d0: Observer: 0x7ff971449b50, Key path: playbackBufferEmpty, Options: <New: YES, Old: YES, Prior: NO> Context: 0x10787e070, Property: 0x7ff97295c090>
<NSKeyValueObservance 0x7ff97295c4d0: Observer: 0x7ff971449b50, Key path: playbackLikelyToKeepUp, Options: <New: YES, Old: YES, Prior: NO> Context: 0x10787e070, Property: 0x7ff97295c300>
<NSKeyValueObservance 0x7ff97295c5d0: Observer: 0x7ff971449b50, Key path: status, Options: <New: YES, Old: YES, Prior: NO> Context: 0x10787e070, Property: 0x7ff97295c540>
```

Not sure what gets deallocated / deinit'd

**Comment by piemonte** [comment]
@freak4pc i can look into a patch, i don't see why it shouldn't support that

**Comment by freak4pc** [comment]
@piemonte , I already solved it locally a couple of hours ago - I'll submit a pull request in a bit ;)

**Comment by piemonte** [comment]
oh nice :clap:

**Comment by piemonte** [comment]
:paperclip: https://github.com/piemonte/Player/pull/7

**Comment by rjgdesign** [comment]
Hey - trying to make a seamless video switch, from one URL to another (its a seamless transition), how can I queue without it flashing before load?

**Comment by freak4pc** [comment]
To be honest, what I did for this was making Player a UIView instead of a UIViewController. It's a bit tricky but can be done pretty quickly and roughly. 

Than I have a "current" player and a "next" player. I load both of them simultaneously and that way I just slide over to the next play by the time the first movie is done playing and the second should usually be loaded by then.

**Comment by otymartin** [comment]
@switz Hey did you manage to figure this out?

**Comment by switz** [comment]
I ended up dropping the project so I haven't looked at it in a long time, but I think I implemented it the way I mentioned it above. Two players that swap when the first is practically finished. I never got it to be perfectly seamless but close enough for my purposes.

I'll take a look at the code when I get home and will be happy to share any code that is useful.

**Comment by otymartin** [comment]
@switz where you streaming? or download and play from local file?
