### ISSUE TITLE
Memory Leak when playing videos?

### ISSUE THREAD

**Issue by sbanil** [piemonte/Player#40]
There may be memory leak in AVPlayer framework i see memory leak when testing the Player Sample app distributed this framework. Here are the screenshots from XCode instruments. You can just run the sample app in Instruments with Leak detector and you will see this behavior.

![image](https://cloud.githubusercontent.com/assets/4535299/11139215/60e2f186-8992-11e5-96c4-422a694ff665.png)
![image](https://cloud.githubusercontent.com/assets/4535299/11139222/7078b3e2-8992-11e5-9e2a-f37d39af6f45.png)
![image](https://cloud.githubusercontent.com/assets/4535299/11139227/7b4fa8c0-8992-11e5-85ac-0fa05b4c559a.png)

**Comment by mayuur** [comment]
It's still leaking in iOS 11 as well. did you find any fix with this issue with AVPlayer?
