### ISSUE TITLE
How to set the player view to a view in a storyboard?

### ISSUE THREAD

**Issue by henrypratt** [piemonte/Player#42]
The example project does not provide a storyboard file, how would I set the player to play from a view in the storyboard with an iboutlet

**Comment by Fredehagelund92** [comment]
Should be pretty straightforward. Create an UiView and set the class to `Player`

**Comment by Matthewspear** [comment]
Quick note for anyone who happens to search storyboard related stuff in the issue section (as I did):

- In storyboard create a container
- Set container's view controller to Player
- Give segue an identifier like "EmbeddedPlayer"
- In main view controller use `prepareForSegue` method:

```swift
override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    if let identifer = segue.identifier
    {
      switch identifer
      {
      case "EmbeddedPlayer":
      
      let player = segue.destinationViewController as! Player
      
      // Setup your player here...
  
      default: break
      }
    }
  }
```

Hope that helps anyone who happens to stumble upon this :)

Matt
