### ISSUE TITLE
How to add control button for the video?

### ISSUE THREAD

**Issue by yuwenhui** [piemonte/Player#44]
I want to add some control button like pause/play,fast forward and rewind, how to do? Should I add my own method in func handleTapGestureRecognizer(), or add the method in the player.swift?

Thanks a lot!

**Comment by sentiasa** [comment]
Hey, did you find anything useful for that approach? 

+1

**Comment by yuwenhui** [comment]
I’ve move to this player: <https://github.com/flexih/CorePlayer.Swift>
