### ISSUE TITLE
Strong reference to PlayerDelegate is not good

### ISSUE THREAD

**Issue by prcela** [piemonte/Player#47]
I have a view controller on navigation stack. That view controller has a player and it is set as a PlayerDelegate. When view controller is removed from stack it is not **deinitialized** because player holds a strong reference to his delegate.

You should change your code to this:

public **weak** var delegate: PlayerDelegate?

public protocol PlayerDelegate: **class** {
...
}

**Comment by misslester** [comment]
commit b4d4a4aeac1761a6362cd0d8fc2251f2f279988b
Author: Leslie Nadeau <leslienadeau@gmail.com>
Date:   Sat Dec 12 23:25:59 2015 -0800

    re-define delegate as weak
    https://github.com/piemonte/Player/issues/47

thx @prcela
