### ISSUE TITLE
Doesn't Play Video on LocalServer

### ISSUE THREAD

**Issue by sentiasa** [piemonte/Player#48]
I am trying to use Player, and I have my back-end API with Lumen (Laravel). I have a video that I found on Vine, that I am going to use in the examples below.

------

First, when I use your direct Vine url,
```
let videoUrl = NSURL(string: "https://v.cdn.vine.co/r/videos/AA3C120C521177175800441692160_38f2cbd1ffb.1.5.13763579289575020226.mp4")!
```
and call `self.player.setUrl(videoUrl)` in ViewDidLoad, it **works**.

-------

Secondly, I downloaded the video file from the Vine link, called it vine.mp4. I dragged it into xCode project directory (+ copy) and included it in 'Copy Bundle Resources'. Then I used:
```
let path = NSBundle.mainBundle().pathForResource("vine", ofType:"mp4")!
let videoUrl = NSURL(fileURLWithPath: path)
```
It **works** again!

-------

**Problem:** Lastly, I tried to add the video to my server and create a route, so I can watch the video directly by using `http://myapi.dev/videos/vine.mp4` on Chrome. But when I try what works for Vine url, **doesn't work** for my api url:

`let videoUrl = NSURL(string: "http://myapi.app/player/vine.mp4")!`

If I `print(videoUrl)`, it gives - `http://myapi.app/player/vine.mp4`.

Just to clarify again, this link is working on Chrome but not in the app. And all the videos used in the 3 approaches above are the same video.

---------

**Addition 1:** Please note that I added this chunk to my info.plist
```
<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>myapi.app</key>
            <dict>
                <key>NSIncludesSubdomains</key>
                <true/>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
```
*Also tried:*
```
 <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
```

---------

**Addition 2:** My route: `$app->get('/player/{filename}', 'PlayerController@show')`
and my Controller method:
```
public function show ($filename)
{
    $this->playVid($filename, 'videos');
}

public function playVid($filename, $showType)
{
    if (file_exists("../uploads/" . $showType . "/" . $filename)) {
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        $type = finfo_file($finfo, "../uploads/" . $showType . "/" . $filename);

        header("Content-Type: " . $type);
        readfile("../uploads/" . $showType . "/" . $filename);
    }
}
```

----------

Video successfully plays in Chrome when I hit that route. But not in the Player demo app.

**Comment by sentiasa** [comment]
Found my problem. It was a server-related problem. I've configured the server properly for video stream handling, and it works like charm!

**Comment by HadiYaac** [comment]
> Found my problem. It was a server-related problem. I've configured the server properly for video stream handling, and it works like charm!

Hi sentiasa, what do you mean by handled the server properly for video streaming? I have a remote url that plays great in browser but player is failing to play it
