### ISSUE TITLE
Buffer Loaded Duration - (Not Issue)

### ISSUE THREAD

**Issue by danbarnes333** [piemonte/Player#5]
Hi,

Incase anyone is in immediate need of a function to find out the buffer available, I inserted the following into player.swift. Simply call it (i.e. `self.player.bufferAvail`) to return the buffered NSTimeInterval. I am using it to decide whether to start playback (on slower connections).

Please note my swift is extremely basic and there is probably a better way of doing this which is a lot better (which I would love to hear!). Because of this I didn't want to put it as a PR.

Thanks

    

    // return available buffer as NSTimeInterval
    public var bufferAvail: NSTimeInterval {

        // Check if there is a player instance
        if ((player.currentItem) != nil) {

            // Get current AVPlayerItem
            var item: AVPlayerItem = player.currentItem
            if (item.status == AVPlayerItemStatus.ReadyToPlay) {
                
                var timeRangeArray: NSArray = item.loadedTimeRanges
                var aTimeRange: CMTimeRange = timeRangeArray.objectAtIndex(0).CMTimeRangeValue
                var startTime = CMTimeGetSeconds(aTimeRange.start)
                var loadedDuration = CMTimeGetSeconds(aTimeRange.duration)
                
                return (NSTimeInterval)(startTime + loadedDuration);
            }
            else {
                return(CMTimeGetSeconds(kCMTimeInvalid))
            }
        } 
        else {
            return(CMTimeGetSeconds(kCMTimeInvalid))
        }
    }

**Comment by piemonte** [comment]
hey @danbarnes333 there is an open pull request on PBJVideoPlayer that may give you some better info:

https://github.com/piemonte/PBJVideoPlayer/pull/19

**Comment by MMasterson** [comment]
Great method! I'll be playing around with this for sure!
