### ISSUE TITLE
Take video screenshots

### ISSUE THREAD

**Issue by kmuchmore** [piemonte/Player#53]
I needed the ability to take a screenshot out of a the video at any point in time. Here's the function I added to accomplish it. Thought you might find it useful.

```
public func screenshot() -> UIImage? {
        let imageGenerator: AVAssetImageGenerator = AVAssetImageGenerator(asset: self.asset)
        if let time = self.player.currentItem?.currentTime() {
            do {
                let ref: CGImage = try imageGenerator.copyCGImageAtTime(time, actualTime: nil)
                let viewImage: UIImage = UIImage(CGImage: ref)
                return viewImage
            } catch {
                print("Something broke")
            }
        }
        return nil
    }
```

**Comment by davidlondono** [comment]
can i use this function for my pod? [https://github.com/davidlondono/PlayerView](https://github.com/davidlondono/PlayerView)

**Comment by kmuchmore** [comment]
Absolutely. Feel free.

Glad it could help.

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/Player/issues/114

this was added in 👍
