### ISSUE TITLE
Progress video cant be found

### ISSUE THREAD

**Issue by davidlondono** [piemonte/Player#54]
i cant find a way to get the duration of the video
 or the buffer loaded of the video
or the place the video is reproducing
or a way to advance the video to a place of the video

**Comment by sentiasa** [comment]
I had the same issue (getting duration, changing the duration of the video with slider) and I achieved it with this answer: http://stackoverflow.com/a/34463369/4705339

Hope this helps

**Comment by davidlondono** [comment]
well, with this issue, i just created a new library for easy use AVPlayer
[https://github.com/davidlondono/PlayerView](https://github.com/davidlondono/PlayerView)
