### ISSUE TITLE
Player stops background music

### ISSUE THREAD

**Issue by xScylez** [piemonte/Player#58]
When the player shows up, it stops the music playing from Spotify and Music app. How can i prevent this?

**Comment by rromanchuk** [comment]
hey @xScylez you can fix this by using Apple's `AVAudioSession`  The default behavior is what you are reporting. 

Here is some helpful information http://stackoverflow.com/a/25221974

**Comment by xScylez** [comment]
It does still not work.. This is my code:

```
self.player = Player()
self.player.delegate = self
player.view.frame.size.width = UIScreen.mainScreen().bounds.size.width
player.view.frame.size.height = player.view.frame.size.width
                
player.fillMode = AVLayerVideoGravityResizeAspectFill
player.view.sizeToFit()
videoCell!.addSubview(player.view)
                
// audio session
let audioSession = AVAudioSession.sharedInstance()
try! audioSession.setCategory(AVAudioSessionCategoryAmbient, withOptions: AVAudioSessionCategoryOptions.MixWithOthers)
                
let videoUrl: NSURL = fileUrl!
self.player.setUrl(videoUrl)
self.player.playFromBeginning()
                
self.player.playbackLoops = true
                
let tapGestureRecognizer: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: "handleTapGestureRecognizer:")
tapGestureRecognizer.numberOfTapsRequired = 1
self.player.view.addGestureRecognizer(tapGestureRecognizer)
```

**Comment by xScylez** [comment]
When the player appears, Spotify and music app music stop playing. I made a Issue earlier, but got closed, and the fix did not work.. Take a look at my code here:

```
self.player = Player()
self.player.delegate = self
player.view.frame.size.width = UIScreen.mainScreen().bounds.size.width
player.view.frame.size.height = player.view.frame.size.width

player.fillMode = AVLayerVideoGravityResizeAspectFill
player.view.sizeToFit()
videoCell!.addSubview(player.view)

// audio session
let audioSession = AVAudioSession.sharedInstance()
try! audioSession.setCategory(AVAudioSessionCategoryAmbient, withOptions: AVAudioSessionCategoryOptions.MixWithOthers)

let videoUrl: NSURL = fileUrl!
self.player.setUrl(videoUrl)
self.player.playFromBeginning()

self.player.playbackLoops = true

let tapGestureRecognizer: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: "handleTapGestureRecognizer:")
tapGestureRecognizer.numberOfTapsRequired = 1
self.player.view.addGestureRecognizer(tapGestureRecognizer)
```

**Comment by rromanchuk** [comment]
@xScylez Is that literally where you are putting your `AVAudioSession` code?  Or just an example? This wouldn't be a very good location in a working app, this should be done well before `Player` ever gets instantiated.

**Comment by xScylez** [comment]
I tried putting it on top of the code gives in my last reply also, but it does not work..

Sent from my iPhone

On 16 Mar 2016, at 16:23, Ryan Romanchuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@xScylez<https://github.com/xScylez> Is that literally where you are putting your AVAudioSession code? Or just an example? This wouldn't be a very good location in a working app, this should be done well before Player ever gets instantiated.

-

**Comment by rromanchuk** [comment]
@xScylez i'll add a working example to the demo project

**Comment by xScylez** [comment]
OK, let me know when it's done.

**Comment by xScylez** [comment]
When are you going to add it? :)

**Comment by adnbsr** [comment]
@xScylez did you solve background playing?
