### ISSUE TITLE
How can I get the Player into the Interface Builder?

### ISSUE THREAD

**Issue by MarcelStructr** [piemonte/Player#65]
I want to resize the player and add constraints to it, because I don't want it to use in fullscreen. I thought the best solution would be to put it into the Interface Builder and customize it there. How can I do that?

If you want, I can also add the question in StackOverflow. But right now it seems, that nobody asks question there, so I put it in here.

**Comment by 131e55** [comment]
Hi @MarcelStructr, sorry for the late response😣
I don't know whether my way is best but I will write it.

First, put a UIContainerView on a view.
Next, embed the Player in the UIContainerView with the Embed segue.
At this time, set any identifier of the Embed segue.
Finaly add constraints to the UIContainerView and use it.

<img width="867" alt="ss1" src="https://cloud.githubusercontent.com/assets/6474348/14515684/40faf120-0237-11e6-81a2-b676001447ce.png">

In source code, get the Player instance in the prepareSegue method and use it.
```
var player: Player!
override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
    if segue.identifier == "Embed_Player" {
        player = segue.destinationViewController as! Player
    }
}
```

I hope this helps you😃
