### ISSUE TITLE
No sound playing on iPhone

### ISSUE THREAD

**Issue by quiKsilverItaly** [piemonte/Player#68]
Hello, 
I just noticed, that there is no sound on the player, when using it on the iPhone. The sound is clearly enabled by default on the iPhone, and other apps work properly.
I used my own app and the sample project and on both there is no sound while the video is playing, BUT on the emulator everything works just fine.

What's the problem here?

**Comment by piemonte** [comment]
@quiKsilverItaly i haven't been able to reproduce this and am getting sound from the sample project
