### ISSUE TITLE
App crashes when dismissing view controller with Player

### ISSUE THREAD

**Issue by hellojeffy** [piemonte/Player#77]
I have a UIViewController that implements the PlayerDelegate.
This UIViewController is displayed using
`self.presentViewController(controller, animated: true, completion: nil)
`

The UIViewController has a Player var that I have
`var videoController: Player!
`
and am playing the video automatically like this
```
videoController = Player()
videoController.delegate = self
videoController.view.frame = self.view.bounds
        
self.addChildViewController(videoController)
self.view.addSubview(videoController.view)
self.view.sendSubviewToBack(videoController.view)
videoController.didMoveToParentViewController(self)
        
let videoUrl: NSURL = url
videoController.setUrl(videoUrl)
videoController.fillMode = "AVLayerVideoGravityResizeAspectFill"
videoController.playFromBeginning()
```

However, when I try to dismiss the presented UIViewController with
`        self.dismissViewControllerAnimated(true, completion: nil)
`

My app always crashes saying 0 _swift_abortRetainUnowned

I tried stopping player playback, similar to another open issue which was resolved through setting a weak delegate, I tried setting delegate to nil but it still crashes, I wasn't sure what else I can do?

**Comment by hellojeffy** [comment]
it also has this in the thread that crashes

```
self.player.addPeriodicTimeObserverForInterval(CMTimeMake(1, 100), queue: dispatch_get_main_queue()) { [unowned self] time in
            self.delegate?.playerCurrentTimeDidChange(self)
        }
```

I thought maybe unowned self needed to be weak self but that didn't solve it.

**Comment by ahusseini** [comment]
The time observer is not removed on deinit.

**Comment by piemonte** [comment]
thanks @hellojeffy @ahusseini 

i'll be able to merge this in next week.
