### ISSUE TITLE
Problem multiple video

### ISSUE THREAD

**Issue by ingouackaz** [piemonte/Player#8]
Hi @piemonte !

I'm trying to use your lib with a TinderSimpleSwipeCards (  https://github.com/cwRichardKim/TinderSimpleSwipeCards ) 

This is the fastest video lib I've found. 

However, when i create 16 card ( 16 Player ), the 17th is not displayed  ... , and i dont know why.

But it works, if i press the home button, then i go back to the application... .

Any idea ?

**Comment by piemonte** [comment]
hey @ingouackaz thanks much. :v: 

i'll check out your library when i have a free moment.

**Comment by MMasterson** [comment]
Same bug, different presentation. I have the videos in a table, after a while they all turn black

**Comment by rromanchuk** [comment]
I have many videos playing at once on a uitableview and uicollectionview just fine.  I keep promising i'll make an example project... i'll try and finish something up by the end of the week

**Comment by thejourneydude** [comment]
Any update on this?

**Comment by ingouackaz** [comment]
Yes, the problem comes from memory. In fact you can't use multiple AVPlayer because they consume  too much memory.

That is why your video screen go black.

Solution : 

I have a pool of only 3 video player, and i switch all video content between each player when i need it.

**Comment by sentiasa** [comment]
@ingouackaz Can you please make a tutorial on how you set up and solved the problem of multiple videos in table view? Cheers

**Comment by ingouackaz** [comment]
Yep i will :)

**Comment by sentiasa** [comment]
@ingouackaz will be waiting :+1:  :)

**Comment by Pelletan** [comment]
@sentiasa , how many items do you have on your tableview ?

Could you exactly explain me what do you want to do with a video tableview ?

**Comment by ingouackaz** [comment]
@sentiasa , how many items do you have on your tableview ?

Could you exactly explain me what do you want to do with a video tableview ?

**Comment by sentiasa** [comment]
The data is coming from an api, so it's like a feed. I think I will try to have thumbnails in the feed and a play button on top of thumbnails, and open another view for the Player.

**Comment by MMasterson** [comment]
@sentiasa - I'm guessing it's a tableview? I suggest using thumbnails, and check to see if the cell is in complete view, and the only cell in complete view to fire the play function.

**Comment by piemonte** [comment]
📎 https://github.com/piemonte/Player/issues/125
