### ISSUE TITLE
Setting up Player for Swift 3.0

### ISSUE THREAD

**Issue by Wouter125** [piemonte/Player#84]
Hi,

I really like your Player library because it's light weight and flexible but I'm running into a small problem. I would like to use it on swift 3.0, but the library isn't ready for that yet. Any chance you can give it a small update or will it cause problems with 2.0+? 

I'm just not such an Xcode expert that I can easily update the player.swift file myself. I'm running into some problems with the KVO, something I never had any experience with.

It's mainly this problem:

``` Expression pattern of type 'Int' cannot match values of type 'UnsafeMutablePointer<Void>?'```

It's like we can't use Int as context... Kinda weird. If you can let me know how to solve this I'm happy as well 😄 

Thanks in advance.

Kind regards,

Wouter

**Comment by piemonte** [comment]
Hi @Wouter125 thanks for the interest! You'll be happy to learn that the library does support Swift 3, it's just on a branch until Swift 3 is released. Then I'll merge it to master. Try it out, let me know if you have problems.

Thanks.

https://github.com/piemonte/Player/tree/swift3
