### ISSUE TITLE
Issue when using nginx secure link

### ISSUE THREAD

**Issue by thetravischannel** [piemonte/Player#85]
When passing a url for an m3u8 playlist with secure link parameters (https://url.net/whatever/index.m3u8?st=*HASH*&e=*TIMESTAMP*), Player seems to be unable to start the stream. The stream works from AVPlayer/AVPlayerLayer just fine, and is accessible from a browser, quicktime, VLC, etc... I have tested this by replacing the URL in the test project with a verified functional link, and it just produces a blank screen. When using the original video from the project, it plays just fine.

**Comment by thetravischannel** [comment]
I have found that for some reason, other HLS streams are (NON secure link) are having this issue too. It appears that the HLS playlist loads correctly, but nothing ever plays. I tried again with the swift 3 branch, and followed the output of my web server's access log, and I can see that Player is requesting and retrieving the ts chunks, but they are not being displayed.

**Comment by piemonte** [comment]
hey @thetravischannel thanks for the note. i don't know what could be causing the issue, but i believe it might be a known problem with AVPlayer.

📎 http://stackoverflow.com/questions/34026175/ios-avplayer-not-loading-most-hls-streams
📎 http://www.openradar.me/16764535
