### ISSUE TITLE
Why is Player UIViewContoller?

### ISSUE THREAD

**Issue by entotsu** [piemonte/Player#94]
What is the reason why Player is not UIView? :grinning: :thought_balloon:

**Comment by piemonte** [comment]
hey @entotsu thanks for the inquiry. i like to keep a lot of view logic thin and without smarts. if Player expanded on it's core feature set in the future and added more advanced features such as other decoding techniques or caching, then that code should more commonly be in a VC.

**Comment by entotsu** [comment]
Great!!
Thank you.
