### ISSUE TITLE
Snapchat like video preview

### ISSUE THREAD

**Issue by otymartin** [piemonte/Player#98]
@piemonte 
I would like to be able to instantly show a preview of a video taken by the user - just like Snapchat and more impressive, Instagram stories. Somehow once a user stops capturing a video on both apps, a preview automatically starts playing in an endless loop seemingly within the same view.

How can I achieve that with `Player`?

**Comment by hellojeffy** [comment]
You can segue to another screen with a Player in it and start playing the video from there.  Then in the playerPlaybackDidEnd delegate, call playFromBeginning

**Comment by otymartin** [comment]
@hellojeffy 
I did that however there is a massive lag, then a black screen shows, all before the video starts playing. Whereas with Snapchat or IG stories, it just shows up magically without any hint that a transition happened.
How is that?

**Comment by hellojeffy** [comment]
I haven't gotten the black screen before replay before, are you passing the NSURL from the capture view to the Player?

Something like this:
```
        player = Player()
        player.delegate = self
        player.view.frame = self.view.bounds
        
        self.addChildViewController(player)
        self.view.addSubview(player.view)
        self.view.sendSubviewToBack(player.view)
        player.didMoveToParentViewController(self)
        
        let videoUrl: NSURL = url // file or http url
        player.setUrl(videoUrl)
        player.fillMode = "AVLayerVideoGravityResizeAspectFill"
       
        player.playFromBeginning()
```

```
    func playerPlaybackDidEnd(player: Player) {
        player.playFromBeginning()
    }
```

**Comment by otymartin** [comment]
@hellojeffy 
Hey I noticed that its not exactly a problem with the replay. Its the actual recording itself. Most videos I take with `cameraEngine` (Which is the library Im using) start with 0.5 second black screen. In other instances, the black screen doesnt exist. Its wierd.

**Comment by otymartin** [comment]
Update: I managed to achieve what I wanted by using a modal segue that displays `over current context`
