### ISSUE TITLE
"playerCurrentTimeDidChange" can't be use in iOS8

### ISSUE THREAD

**Issue by entotsu** [piemonte/Player#99]
What is a reason why [update iOS deployment target to iOS9](https://github.com/piemonte/Player/commit/4aa1c627501d0e6db37444a23078973990ea7730)? 😢

**Comment by piemonte** [comment]
hey @entotsu :v:

you can still use the previous tag of `Player` in your app for iOS 8 support. with iOS 10 soon here, the < 10% user base will become even smaller. i'll add in TimeDidChange-like functionality for iOS 9.

https://developer.apple.com/support/app-store/
